name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Navigate to the React app directory and install dependencies
    - name: Install dependencies
      run: npm install
      working-directory: ReactApp_Testing/To_do_app

    # Step 4: Build the React app
    - name: Build the app
      run: npm run build
      working-directory: ReactApp_Testing/To_do_app

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ReactApp_Testing/To_do_app/build
