# Workflow name
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Use Node.js version 20
          cache: npm
          cache-dependency-path: To_do_app/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: To_do_app  # Navigate to the project folder

      # Step 4: Build the React app
      - name: Build the app
        run: npm run build
        working-directory: To_do_app  # Navigate to the project folder

      # Step 5: Configure GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # Step 6: Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: To_do_app/build  # Path to the build folder

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
